server:
    port: 8888
encrypt:
  key: ABCDEFGHIJKLMNOPQRSTUVWXYZ
spring:
    security:
        user:
            name: pluralsight
            password: pluralsight
    cloud:
        config:
            server:
                encrypt:
                    enabled: false
                git:
                    uri: https://github.com/rseroter/pluralsight-spring-cloudconfig-wa-tolls-2
                    search-paths:
                    - station*
                    repos:
                        perf:
                            pattern: '*/perf'
                            uri: https://github.com/rseroter/pluralsight-spring-cloudconfig-wa-tolls-perf-2
                            search-paths:
                            - 'station*'                    